import { UploadedScreenshot } from '../storage/index.js'

export interface GitHubCommentOptions {
  /** Uploaded screenshots to display */
  screenshots: UploadedScreenshot[]
  /** PR number */
  prNumber: number
  /** GitHub token for authentication */
  token: string
  /** Repository owner */
  owner: string
  /** Repository name */
  repo: string
  /** Run ID for linking to the workflow */
  runId?: string | number
  /** Repository HTML URL */
  repositoryUrl?: string
}

/**
 * Generate markdown comment body for GitHub PR
 */
export function generateCommentBody(options: GitHubCommentOptions): string {
  const { screenshots, runId, repositoryUrl } = options

  let commentBody = '## 📸 UI Screenshots\n\n'
  commentBody += 'Automated screenshots from the latest build:\n\n'

  for (const screenshot of screenshots) {
    const displayName = screenshot.name
      .replace('.png', '')
      .replace(/-/g, ' ')
      .replace(/_/g, ' ')

    commentBody += `### ${displayName}\n`
    commentBody += `![${displayName}](${screenshot.url})\n\n`
  }

  commentBody += '\n---\n'

  if (runId && repositoryUrl) {
    commentBody += `🤖 Generated by [GitHub Actions](${repositoryUrl}/actions/runs/${runId})`
  } else {
    commentBody += '🤖 Generated by automated screenshot workflow'
  }

  return commentBody
}

/**
 * Post or update a GitHub PR comment with screenshots
 * Note: This function is designed to be called from a GitHub Actions workflow
 * using actions/github-script@v7, as it requires the GitHub API client.
 *
 * For a complete example, see the README.
 */
export async function postToGitHub(
  options: GitHubCommentOptions,
  githubClient: any
): Promise<void> {
  const { screenshots, prNumber, owner, repo } = options

  if (screenshots.length === 0) {
    throw new Error('No screenshots provided')
  }

  const commentBody = generateCommentBody(options)

  // Find existing comment
  const { data: comments } = await githubClient.rest.issues.listComments({
    owner,
    repo,
    issue_number: prNumber,
  })

  const botComment = comments.find((comment: any) =>
    comment.user.type === 'Bot' &&
    comment.body.includes('📸 UI Screenshots')
  )

  // Update or create comment
  if (botComment) {
    await githubClient.rest.issues.updateComment({
      owner,
      repo,
      comment_id: botComment.id,
      body: commentBody
    })
    console.log('✓ Updated existing PR comment')
  } else {
    await githubClient.rest.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body: commentBody
    })
    console.log('✓ Created new PR comment')
  }
}
