import { UploadedScreenshot } from '../storage/index.js'

export interface GitHubCommentOptions {
  /** Uploaded screenshots to display */
  screenshots: UploadedScreenshot[]
  /** PR number */
  prNumber: number
  /** GitHub token for authentication */
  token: string
  /** Repository owner */
  owner: string
  /** Repository name */
  repo: string
  /** Run ID for linking to the workflow */
  runId?: string | number
  /** Repository HTML URL */
  repositoryUrl?: string
}

/**
 * Format a screenshot filename into a human-readable display name
 */
function formatDisplayName(name: string): string {
  return name
    .replace('.png', '')
    .replace(/-/g, ' ')
    .replace(/_/g, ' ')
}

/**
 * Generate a thumbnail grid table for a set of screenshots
 * Uses 3-column layout with clickable thumbnails
 */
function generateThumbnailGrid(screenshots: UploadedScreenshot[]): string {
  if (screenshots.length === 0) return ''

  let grid = '| | | |\n'
  grid += '|---|---|---|\n'

  for (let i = 0; i < screenshots.length; i += 3) {
    const row = screenshots.slice(i, i + 3)
    const cells = row.map(s => {
      const displayName = formatDisplayName(s.name)
      return `<a href="${s.url}"><img src="${s.url}" width="280"><br>${displayName}</a>`
    })
    // Pad with empty cells if needed
    while (cells.length < 3) {
      cells.push('')
    }
    grid += `| ${cells.join(' | ')} |\n`
  }

  return grid
}

/**
 * Generate markdown comment body for GitHub PR
 * Groups screenshots by category and renders them as a thumbnail grid
 */
export function generateCommentBody(options: GitHubCommentOptions): string {
  const { screenshots, runId, repositoryUrl } = options

  let commentBody = '## 📸 UI Screenshots\n\n'
  commentBody += 'Automated screenshots from the latest build:\n\n'

  const hasGroups = screenshots.some(s => s.group)

  if (hasGroups) {
    // Group screenshots by their group field
    const groups = new Map<string, UploadedScreenshot[]>()
    for (const screenshot of screenshots) {
      const group = screenshot.group || 'Other'
      if (!groups.has(group)) {
        groups.set(group, [])
      }
      groups.get(group)!.push(screenshot)
    }

    for (const [group, groupScreenshots] of groups) {
      const count = groupScreenshots.length
      commentBody += `<details>\n`
      commentBody += `<summary><strong>${group}</strong> (${count} screenshot${count !== 1 ? 's' : ''})</summary>\n\n`
      commentBody += generateThumbnailGrid(groupScreenshots)
      commentBody += '\n</details>\n\n'
    }
  } else {
    // No groups - just show the grid directly
    commentBody += generateThumbnailGrid(screenshots)
  }

  commentBody += '\n---\n'

  if (runId && repositoryUrl) {
    commentBody += `🤖 Generated by [GitHub Actions](${repositoryUrl}/actions/runs/${runId})`
  } else {
    commentBody += '🤖 Generated by automated screenshot workflow'
  }

  return commentBody
}

/**
 * Post or update a GitHub PR comment with screenshots
 * Note: This function is designed to be called from a GitHub Actions workflow
 * using actions/github-script@v7, as it requires the GitHub API client.
 *
 * For a complete example, see the README.
 */
export async function postToGitHub(
  options: GitHubCommentOptions,
  githubClient: any
): Promise<void> {
  const { screenshots, prNumber, owner, repo } = options

  if (screenshots.length === 0) {
    throw new Error('No screenshots provided')
  }

  const commentBody = generateCommentBody(options)

  // Find existing comment
  const { data: comments } = await githubClient.rest.issues.listComments({
    owner,
    repo,
    issue_number: prNumber,
  })

  const botComment = comments.find((comment: any) =>
    comment.user.type === 'Bot' &&
    comment.body.includes('📸 UI Screenshots')
  )

  // Update or create comment
  if (botComment) {
    await githubClient.rest.issues.updateComment({
      owner,
      repo,
      comment_id: botComment.id,
      body: commentBody
    })
    console.log('✓ Updated existing PR comment')
  } else {
    await githubClient.rest.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body: commentBody
    })
    console.log('✓ Created new PR comment')
  }
}
