import { test, expect } from '@playwright/test'
import { generateCommentBody } from '../src/github/comment.js'
import type { UploadedScreenshot } from '../src/storage/index.js'

test.describe('generateCommentBody', () => {
  test('should generate comment body with screenshots', () => {
    const screenshots: UploadedScreenshot[] = [
      { name: 'homepage.png', url: 'https://example.com/homepage.png', path: 'pr-123/homepage.png' },
      { name: 'dashboard.png', url: 'https://example.com/dashboard.png', path: 'pr-123/dashboard.png' },
    ]

    const comment = generateCommentBody({
      screenshots,
      prNumber: 123,
      token: 'fake-token',
      owner: 'test-owner',
      repo: 'test-repo',
    })

    expect(comment).toContain('## 📸 UI Screenshots')
    expect(comment).toContain('homepage.png')
    expect(comment).toContain('dashboard.png')
    expect(comment).toContain('https://example.com/homepage.png')
    expect(comment).toContain('https://example.com/dashboard.png')
  })

  test('should format screenshot names nicely', () => {
    const screenshots: UploadedScreenshot[] = [
      { name: 'my-homepage-screenshot.png', url: 'https://example.com/img.png', path: 'path.png' },
      { name: 'dashboard_view.png', url: 'https://example.com/img2.png', path: 'path2.png' },
    ]

    const comment = generateCommentBody({
      screenshots,
      prNumber: 123,
      token: 'fake-token',
      owner: 'test-owner',
      repo: 'test-repo',
    })

    expect(comment).toContain('### my homepage screenshot')
    expect(comment).toContain('### dashboard view')
  })

  test('should include run ID link when provided', () => {
    const screenshots: UploadedScreenshot[] = [
      { name: 'test.png', url: 'https://example.com/test.png', path: 'test.png' },
    ]

    const comment = generateCommentBody({
      screenshots,
      prNumber: 123,
      token: 'fake-token',
      owner: 'test-owner',
      repo: 'test-repo',
      runId: '456789',
      repositoryUrl: 'https://github.com/test-owner/test-repo',
    })

    expect(comment).toContain('GitHub Actions')
    expect(comment).toContain('https://github.com/test-owner/test-repo/actions/runs/456789')
  })

  test('should include fallback text when run ID not provided', () => {
    const screenshots: UploadedScreenshot[] = [
      { name: 'test.png', url: 'https://example.com/test.png', path: 'test.png' },
    ]

    const comment = generateCommentBody({
      screenshots,
      prNumber: 123,
      token: 'fake-token',
      owner: 'test-owner',
      repo: 'test-repo',
    })

    expect(comment).toContain('🤖 Generated by automated screenshot workflow')
    expect(comment).not.toContain('GitHub Actions')
  })

  test('should handle empty screenshots array', () => {
    const comment = generateCommentBody({
      screenshots: [],
      prNumber: 123,
      token: 'fake-token',
      owner: 'test-owner',
      repo: 'test-repo',
    })

    expect(comment).toContain('## 📸 UI Screenshots')
    expect(comment).toContain('Automated screenshots from the latest build')
  })

  test('should handle special characters in screenshot names', () => {
    const screenshots: UploadedScreenshot[] = [
      { name: 'test@123#special.png', url: 'https://example.com/test.png', path: 'test.png' },
    ]

    const comment = generateCommentBody({
      screenshots,
      prNumber: 123,
      token: 'fake-token',
      owner: 'test-owner',
      repo: 'test-repo',
    })

    // The function removes .png extension and replaces -/_ with spaces for display
    expect(comment).toContain('test@123#special')
    expect(comment).toContain('https://example.com/test.png')
  })
})

